services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5532:5532
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 5532
volumes:
  pgdata:
